/**
 * Byte-parity gate against the upstream this package replaces.
 *
 * `test/fixtures/baseline-0.1.1.json` was generated by running the 50-case
 * corpus through `remark-mark-highlight@0.1.1` BEFORE core swapped to this
 * package — it is the independent tokenizer oracle (after the swap,
 * byteEquivalence's legacy mirror shares this implementation and can no
 * longer catch a tokenizer-level divergence). Every case asserts deep
 * equality of BOTH the mdast (positions included) and the hast.
 */
import { readFileSync } from 'node:fs';
import type { Root } from 'mdast';
import { describe, expect, test } from 'vitest';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkStringify from 'remark-stringify';
import { toHast } from 'mdast-util-to-hast';
import { remarkMarkHighlight, remarkMark } from './index.js';

interface BaselineCase {
  input: string;
  mdast: unknown;
  hast: unknown;
}

const baseline = JSON.parse(readFileSync(new URL('../test/fixtures/baseline-0.1.1.json', import.meta.url), 'utf8')) as {
  cases: BaselineCase[];
};

const proc = unified().use(remarkParse).use(remarkMarkHighlight);

describe('parity with remark-mark-highlight@0.1.1 (independent baseline)', () => {
  test('corpus is intact', () => {
    expect(baseline.cases.length).toBe(50);
  });

  for (const { input, mdast, hast } of baseline.cases) {
    test(JSON.stringify(input.slice(0, 40)), () => {
      const tree = proc.runSync(proc.parse(input)) as Root;
      expect(JSON.parse(JSON.stringify(tree))).toEqual(mdast);
      expect(JSON.parse(JSON.stringify(toHast(tree)))).toEqual(hast);
    });
  }
});

describe('plugin surface', () => {
  test('the upstream export name is aliased', () => {
    expect(remarkMark).toBe(remarkMarkHighlight);
  });

  test('serialization round-trips ==mark==', () => {
    const rt = unified().use(remarkParse).use(remarkStringify).use(remarkMarkHighlight);
    const out = String(rt.processSync('a ==b **c**== d'));
    expect(out.trim()).toBe('a ==b **c**== d');
  });

  test('a lone = is not swallowed by serialization escaping inside a mark', () => {
    const rt = unified().use(remarkParse).use(remarkStringify).use(remarkMarkHighlight);
    const out = String(rt.processSync('==a=b=='));
    expect(String(rt.processSync(out)).trim()).toBe(out.trim());
  });
});
